multiasset info query accepts asset name in hex
Emurgo/yoroi-graphql-migration-backend pull request #376
Opened 2022-07-07 16:18 UTC by yushih

Originally the multi-asset metadata endpoint `multiAsset/metadata` takes parameters in this form:
```
{
  "assets":[
     {"name":"...", "policy": "..."},
     ...
  ]
}
```
And the "name" is the asset name in hex decoded as an ASCII string.
The problem is that the blockchain protocol does not mandate the name to an ASCII string, nor even an UTF8 string. For example:
https://testnet.cardanoscan.io/tokens?pageNo=12&policyId=b940743438a9217ea9d673362f708e5080dcd7b597988ae962782e10. So a query containing a token with name like `ab6854726b0139254b7e5c4831c87ac043a938fa3543b5eb0ce0906e122083e9` leads to the PSQL error "invalid input syntax for type bytea".

This PR accepts the asset name in a hex string as the `nameHex` field.
```
{
  "assets":[
     {"nameHex":"...", "policy": "..."},
     ...
  ]
}
```
For backward-compatibity, `name` is also accept and the semantics aren't changed.

2022-07-07 18:02 UTC, stackchain requested changes
@yushih nice catch! could you please update the `README.md`?

2022-07-08 14:19 UTC, yushih commented
@stackchain Right, I forgot!  Doc updated.

2022-07-11 13:51 UTC, pedromtcosta commented
@stackchain could you update your review now that @yushih updated the docs please?

2022-07-11 21:05 UTC, stackchain approved these changes

2022-07-12 15:23 UTC, vsubhuman approved these changes

2022-07-12 16:01 UTC, vsubhuman reviewed
/check

2022-07-12 16:11 UTC, merged